# Form implementation generated from reading ui file 'qcrop.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import logging as log

from PyQt6.QtWidgets import QWidget, QLabel, QRubberBand
from PyQt6.QtGui import QPainter, QBrush, QColor, QPalette
from PyQt6.QtCore import QRect, QSize, QPoint, QMargins, pyqtSignal, Qt
from PyQt6 import QtCore, QtGui, QtWidgets


class BaseUiQCrop(object):

    def __init__(self, QCrop):
        QCrop.setObjectName("QCrop")
        QCrop.resize(664, 576)
        QCrop.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(QCrop)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolbar = QtWidgets.QWidget(parent=QCrop)
        self.toolbar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolbar.setObjectName("toolbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.toolbar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelX = QtWidgets.QLabel(parent=self.toolbar)
        self.labelX.setObjectName("labelX")
        self.horizontalLayout.addWidget(self.labelX)
        self.spinBoxX = QtWidgets.QSpinBox(parent=self.toolbar)
        self.spinBoxX.setMinimumSize(QtCore.QSize(72, 0))
        self.spinBoxX.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTrailing |
            QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.spinBoxX.setObjectName("spinBoxX")
        self.horizontalLayout.addWidget(self.spinBoxX)
        self.labelY = QtWidgets.QLabel(parent=self.toolbar)
        self.labelY.setObjectName("labelY")
        self.horizontalLayout.addWidget(self.labelY)
        self.spinBoxY = QtWidgets.QSpinBox(parent=self.toolbar)
        self.spinBoxY.setMinimumSize(QtCore.QSize(72, 0))
        self.spinBoxY.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTrailing |
            QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.spinBoxY.setObjectName("spinBoxY")
        self.horizontalLayout.addWidget(self.spinBoxY)
        self.labelW = QtWidgets.QLabel(parent=self.toolbar)
        self.labelW.setObjectName("labelW")
        self.horizontalLayout.addWidget(self.labelW)
        self.spinBoxW = QtWidgets.QSpinBox(parent=self.toolbar)
        self.spinBoxW.setMinimumSize(QtCore.QSize(72, 0))
        self.spinBoxW.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTrailing |
            QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.spinBoxW.setObjectName("spinBoxW")
        self.horizontalLayout.addWidget(self.spinBoxW)
        self.labelH = QtWidgets.QLabel(parent=self.toolbar)
        self.labelH.setObjectName("labelH")
        self.horizontalLayout.addWidget(self.labelH)
        self.spinBoxH = QtWidgets.QSpinBox(parent=self.toolbar)
        self.spinBoxH.setMinimumSize(QtCore.QSize(72, 0))
        self.spinBoxH.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTrailing |
            QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.spinBoxH.setObjectName("spinBoxH")
        self.horizontalLayout.addWidget(self.spinBoxH)
        spacer_item = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacer_item)
        self.pushButton = QtWidgets.QPushButton(parent=self.toolbar)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.toolbar)
        self.line = QtWidgets.QFrame(parent=QCrop)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.scrollArea = QtWidgets.QScrollArea(parent=QCrop)
        self.scrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.scrollArea.setAutoFillBackground(True)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.workspace = Workspace()
        self.workspace.setGeometry(QtCore.QRect(0, 0, 638, 478))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.workspace.setPalette(palette)
        self.workspace.setObjectName("workspace")
        self.gridLayout = QtWidgets.QGridLayout(self.workspace)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacer_item1 = QtWidgets.QSpacerItem(20, 224, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacer_item1, 2, 2, 1, 1)
        spacer_item2 = QtWidgets.QSpacerItem(304, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacer_item2, 1, 3, 1, 1)
        self.frame = QtWidgets.QFrame(parent=self.workspace)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.selector = AreaSelector(parent=self.frame)
        self.selector.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.selector.setText("")
        self.selector.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.selector.setObjectName("selector")
        self.verticalLayout_2.addWidget(self.selector)
        self.gridLayout.addWidget(self.frame, 1, 2, 1, 1)
        spacer_item3 = QtWidgets.QSpacerItem(305, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacer_item3, 1, 0, 1, 1)
        spacer_item4 = QtWidgets.QSpacerItem(20, 225, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacer_item4, 0, 2, 1, 1)
        self.scrollArea.setWidget(self.workspace)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=QCrop)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel | QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.__re_translate_ui(QCrop)
        self.buttonBox.accepted.connect(QCrop.accept)  # type: ignore
        self.buttonBox.rejected.connect(QCrop.reject)  # type: ignore
        self.selector.area_changed.connect(QCrop.update_crop_values)  # type: ignore
        self.spinBoxX.valueChanged['int'].connect(QCrop.update_crop_area)  # type: ignore
        self.spinBoxY.valueChanged['int'].connect(QCrop.update_crop_area)  # type: ignore
        self.spinBoxW.valueChanged['int'].connect(QCrop.update_crop_area)  # type: ignore
        self.spinBoxH.valueChanged['int'].connect(QCrop.update_crop_area)  # type: ignore
        self.pushButton.clicked.connect(QCrop.reset_crop_values)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(QCrop)

    def __re_translate_ui(self, QCrop):
        _translate = QtCore.QCoreApplication.translate
        QCrop.setWindowTitle(_translate("QCrop", "QCrop"))
        self.labelX.setText(_translate("QCrop", "X:"))
        self.spinBoxX.setSuffix(_translate("QCrop", "px"))
        self.labelY.setText(_translate("QCrop", "Y:"))
        self.spinBoxY.setSuffix(_translate("QCrop", "px"))
        self.labelW.setText(_translate("QCrop", "Width:"))
        self.spinBoxW.setSuffix(_translate("QCrop", "px"))
        self.labelH.setText(_translate("QCrop", "Height:"))
        self.spinBoxH.setSuffix(_translate("QCrop", "px"))
        self.pushButton.setText(_translate("QCrop", "Reset"))


class AreaSelector(QLabel):
    area_changed = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self.crop = QRect(0, 0, 0, 0)
        # parent is the QFrame, its parent is the Workspace
        parent.parent().selector = self

    def paintEvent(self, event):
        super().paintEvent(event)

        qp = QPainter(self)
        qp.setBrush(QBrush(QColor(0, 0, 0, 200)))
        qp.setPen(Qt.PenStyle.NoPen)

        for r in AreaSelector.exclude(self.geometry().translated(-1, -1), self.crop):
            qp.drawRect(r)

    @staticmethod
    def exclude(outer, inner):
        """
        :param outer: the external rectangle as a QRect object
        :param inner: the inner rectangle as a QRect object
        :return: a tuple of four QRect objects, representing the frame of the inner rect
            +----+--------------+--------+
            | 11 | 222222222222 | 444444 |
            | 11 +--------------+ 444444 |
            | 11 |              | 444444 |
            | 11 |              | 444444 |
            | 11 |              | 444444 |
            | 11 +--------------+ 444444 |
            | 11 | 333333333333 | 444444 |
            | 11 | 333333333333 | 444444 |
            +----+--------------+--------+
        """
        # just in case the inner rect goes beyond the outer limits
        log.debug('OUTER:')
        log.debug(outer)
        log.debug('INNER:')
        log.debug(inner)
        inner = outer.intersected(inner)
        areas = (
            QRect(outer.left(), outer.top(), inner.left(), outer.height()),
            QRect(inner.left(), outer.top(), inner.width(), inner.top()),
            QRect(inner.left(), inner.bottom() + 1, inner.width(), outer.height() - inner.bottom() - 1),
            QRect(inner.right() + 1, outer.top(), outer.width() - inner.right() + 1, outer.height())
        )
        log.debug('AREAS:')
        log.debug(areas)
        return areas


class Workspace(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)

        self._rubberband = None
        self._origin = None
        self.selector = None

        p = QPalette()
        p.setColor(QPalette.ColorRole.Window, QColor(0, 0, 0))  # Set color to black
        self.setPalette(p)

    def mousePressEvent(self, event):
        if not self._rubberband:
            self._rubberband = QRubberBand(QRubberBand.Shape.Rectangle, self)
        self._origin = event.pos()
        self.selector.crop = QRect(QPoint(0, 0), self.selector.geometry().size())
        self.repaint()
        self._rubberband.setGeometry(QRect(self._origin, QSize()))
        self._rubberband.show()

    def mouseMoveEvent(self, event):
        selection = QRect(self._origin, event.pos()).normalized()
        self._rubberband.setGeometry(selection)

    def mouseReleaseEvent(self, event):
        selection = QRect(self._origin, event.pos()).normalized()
        full_image = self.selector.parent().geometry() - QMargins(1, 1, 1, 1)
        self.selector.crop = selection.intersected(full_image).translated(-full_image.topLeft())
        self._rubberband.setGeometry(selection)
        self._rubberband.hide()
        self.repaint()
        self.selector.area_changed.emit()
